### ISSUE TITLE
Android project as sample

### ISSUE THREAD

**Issue by abhi007tyagi** [googleapis/java-dialogflow#182]
*Is your feature request related to a problem? Please describe.**
Proper Android samples not available

**Describe the solution you'd like**
Share my project for others to take a look and integrate Dialogflow within their Android code
https://github.com/abhi007tyagi/DialogflowChat

**Comment by munkhuushmgl** [comment]
@abhi007tyagi Is this related to #181?

**Comment by munkhuushmgl** [comment]
According to our doc, android currently not support 
https://github.com/googleapis/google-cloud-java#supported-platforms

With this note, closing this issue.

**Comment by abhi007tyagi** [comment]
@gguuss @munkhuushmgl I have created a [library to add Dialogflow chat into Android](https://medium.com/@abhi007tyagi/android-dialogflow-chatbot-library-6b7b3822e7bc) . I know this is not supported as of now by Google but it may help. Please try at your end :)
If possible add this as sample so that others can use it.

**Comment by munkhuushmgl** [comment]
@abhi007tyagi Have you got a chance to look at this repo? https://github.com/GoogleCloudPlatform/android-docs-samples/tree/master/dialogflow

**Comment by abhi007tyagi** [comment]
@munkhuushmgl  No, I didn't :( 
I was told recently that Google Cloud Java does not support Android for Dialogflow right now. I had started working on this last year but got delayed due to work. I am always late releasing libraries :(

**Comment by abhi007tyagi** [comment]
@munkhuushmgl @gguuss My library is a bit different in use. First of all, its a library so no UI coding or any other chat setup. Secondly, the UI can be controlled from the Webhook code similar to Google Assistant.
