### ISSUE TITLE
java.lang.IllegalArgumentException: FieldDescriptor does not match message type

### ISSUE THREAD

**Issue by Kamatam** [googleapis/java-dialogflow#183]
Hi Team,

I am trying to build the following WebhookResponse payload  as is and which includes richResponse like basicCard, etc using java com.google.cloud.dialogflow.v2.*  apis but getting into "FieldDescriptor does not match message type" issue. 

Api documentation:

http://googleapis.github.io/googleapis/java/all/latest/apidocs/index.html?com/google/cloud/dialogflow/v2/WebhookResponse.Builder.html

payload ( mentioned in "setPayload" method from above api documentation)
------------
{
		   "google": {
		     "expectUserResponse": true,
		     "richResponse": {
		       "items": [
		         {
		           "simpleResponse": {
		             "textToSpeech": "this is a simple response"
		           }
		         }
		       ]
		     }
		   }
		 }

Please find the following code snippet and correct me if i am missing anything. Appreciate your suggestions and inputs.

import com.google.cloud.dialogflow.v2.Intent;
import com.google.cloud.dialogflow.v2.Intent.Message;
import com.google.cloud.dialogflow.v2.Intent.Message.BasicCard;
import com.google.cloud.dialogflow.v2.Intent.Message.Image;
import com.google.cloud.dialogflow.v2.QueryResult;
import com.google.cloud.dialogflow.v2.WebhookResponse;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.ListValue;
import com.google.protobuf.Struct;
import com.google.protobuf.Value;

/*
*
* http://googleapis.github.io/googleapis/java/all/latest/apidocs/index.html?com/google/cloud/dialogflow/v2/WebhookResponse.Builder.html
*
* {
"google": {
"expectUserResponse": true,
"richResponse": {
"items": [
{
"simpleResponse": {
"textToSpeech": "this is a simple response"
}
}
]
}
}
}
*/

public static void buildWebhookPayload(String apiResponse)
		throws ConversationException {
	
	
	Struct.Builder payload = Struct.newBuilder();
	Struct.Builder google = Struct.newBuilder();
	ListValue.Builder messageList = ListValue.newBuilder();
	Message.Builder message = Message.newBuilder();
	BasicCard.Builder basicCard = BasicCard.newBuilder();
	basicCard.setFormattedText(apiResponse); // api response, 
	basicCard.setTitle("Card title");
	Image.Builder image = Image.newBuilder();
	image.setImageUri("http://test.jpg");
	basicCard.setImage(image);
	message.setBasicCard(basicCard);
	
	FieldDescriptor fieldDesc = Message.getDescriptor()
			.findFieldByNumber(Message.BASIC_CARD_FIELD_NUMBER);	
	messageList.addValuesBuilder().setField(fieldDesc, message.build()); //  This line causing java.lang.IllegalArgumentException: FieldDescriptor does not match message type.
	google.putFields("richResponse", Value.newBuilder().setListValue(messageList).build());
	payload.putFields("google", Value.newBuilder().setStructValue(google).build());
	WebhookResponse webhookResp = WebhookResponse.newBuilder().setPayload(payload).build();	
}

**Comment by athakor** [comment]
@Kamatam can you please try below sample code, may be it's unblock you from above situation

**Sample:**
```javascript
import com.google.cloud.dialogflow.v2.Intent.Message;
import com.google.cloud.dialogflow.v2.Intent.Message.BasicCard;
import com.google.cloud.dialogflow.v2.Intent.Message.Image;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.ListValue;
import com.google.protobuf.Struct;
import com.google.protobuf.Value;


public class Test {
    private static final String FORMATTED_TEXT = "This is a basic card";
    private static final String API_RESPONSE = "{\n" +
            "   \"google\": {\n" +
            "     \"expectUserResponse\": true,\n" +
            "     \"richResponse\": {\n" +
            "       \"items\": [\n" +
            "         {\n" +
            "           \"simpleResponse\": {\n" +
            "             \"textToSpeech\": \"this is a simple response\"\n" +
            "           }\n" +
            "         }\n" +
            "       ]\n" +
            "     }\n" +
            "   }\n" +
            " }";

    public static void main(String[] args) {
        buildWebhookPayload(API_RESPONSE);
    }

    public static void buildWebhookPayload(String apiResponse) {
        Struct.Builder payload = Struct.newBuilder();
        Struct.Builder google = Struct.newBuilder();
        ListValue.Builder messageList = ListValue.newBuilder();
        Image.Builder image = Image.newBuilder().setImageUri("https://storage.googleapis.com/actionsresources/logo_assistant_2x_64dp.png").setAccessibilityText("Image alternate text");
        BasicCard.Builder basicCard = BasicCard.newBuilder()
                .setTitle("This is a title")
                .setSubtitle("This is a subtitle")
                .setFormattedText("Card formatted text")
                .setImage(image.build())
                .addButtons(BasicCard.Button.newBuilder().setTitle("This is a Button").setOpenUriAction(BasicCard.Button.OpenUriAction.newBuilder().setUri("https://assistant.google.com").build()).build());
        Message.Builder message = Message.newBuilder().setBasicCard(basicCard.build());
        FieldDescriptor fieldDesc = Message.getDescriptor().findFieldByNumber(Message.BASIC_CARD_FIELD_NUMBER);
        messageList.addValuesBuilder().setStringValue(message.build().toString());
        google.putFields("richResponse", Value.newBuilder().setListValue(messageList).build());
        payload.putFields("google", Value.newBuilder().setStructValue(google).build());
        WebhookResponse webhookResp = WebhookResponse.newBuilder().setPayload(payload).build();
        System.out.println(webhookResp);
    }
}
```
**Response:**
```javascript
payload {
  fields {
    key: "google"
    value {
      struct_value {
        fields {
          key: "richResponse"
          value {
            list_value {
              values {
                string_value: "basic_card {\n  title: \"This is a title\"\n  subtitle: \"This is a subtitle\"\n  formatted_text: \"Card formatted text\"\n  image {\n    image_uri: \"https://storage.googleapis.com/actionsresources/logo_assistant_2x_64dp.png\"\n    accessibility_text: \"Image alternate text\"\n  }\n  buttons {\n    title: \"This is a Button\"\n    open_uri_action {\n      uri: \"https://assistant.google.com\"\n    }\n  }\n}\n"
              }
            }
          }
        }
      }
    }
  }
}

```
Let me know if  this works for you.

**Comment by athakor** [comment]
i am closing this issue, feel free to reopen if above comment didn' help
