### ISSUE TITLE
No docs published for latest library version (2.0.0)

### ISSUE THREAD

**Issue by danoscarmike** [googleapis/java-dialogflow#196]
[Latest available docs are for 1.0.0](https://googleapis.dev/java/google-cloud-dialogflow/latest/index.html)

[Version 2.0.0 was released](https://github.com/googleapis/java-dialogflow/releases/tag/v2.0.0) last month

**Comment by b-loved-dreamer** [comment]
Docs versions are now published for [3.0.1](https://googleapis.dev/java/google-cloud-dialogflow/latest/index.html) on its respective [released](https://github.com/googleapis/java-dialogflow/releases) version. I am now closing this issue due to it not being relevant.
