### ISSUE TITLE
Missing connections behind proxy 

### ISSUE THREAD

**Issue by MarioAnastasi** [googleapis/java-dialogflow#21]
Hi Guys,

i have a problem with last verison of google-cloud-dialogflow. I recive a timeout when i try to open a connection behind a proxy.

The excepiont is:
 io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed while performing protocol negotiation for [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$WaitUntilActiveHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
inail.dashboard.exceptions.ChatbotException: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed while performing protocol negotiation for [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$WaitUntilActiveHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]

The issue is caused by changes in io.grpc.netty.ProtocolNegotiators. Replacing this file in 1.23.0 with the one from 1.21.0 (with some minor compile fixes) restores the functionality.

https://github.com/grpc/grpc-java/issues/6118

Is it possible create a new version that include as dependencies the versione 1.24.1 of grpc-netty-shaded?

Regards.

**Comment by codyoss** [comment]
Hey thanks for the report I will try to get a release cut soon.

**Comment by codyoss** [comment]
@MarioAnastasi @nareshgnT This will be fixed once this PR is merged in a few minutes https://github.com/googleapis/java-dialogflow/pull/23

**Comment by codyoss** [comment]
A new release has been cut.

**Comment by waytoalpit** [comment]
Facing exactly the same error with /io/grpc/grpc-netty-shaded/1.25.0/grpc-netty-shaded-1.25.0.jar!. Can someone point out with the fix?
