### ISSUE TITLE
Dialogflow V2 Agent Versioning on Java Client

### ISSUE THREAD

**Issue by UncleFirefox** [googleapis/java-dialogflow#24]
Hi, I created a question on StackOverflow regarding the versioning of environments and its access through the Java client, which doesn't seem to be accessible at the moment. 

https://stackoverflow.com/questions/58059832/dialogflow-v2-agent-versioning-on-java-client

Can you help me?

Thanks

**Comment by UncleFirefox** [comment]
Hi, is there anybody who could help us on this? We have different environments and we'd really like to start using this feature...

**Comment by b-loved-dreamer** [comment]
Hi @UncleFirefox — I found this [reading](https://cloud.google.com/dialogflow/es/docs/agents-versions), potentially useful for this issue. If still relevant, please take a look.

I am closing this issue. Please, reopen if needed.
