### ISSUE TITLE
Não é possível utilizar juntamente com o Firestore no Android

### ISSUE THREAD

**Issue by ReniDelonzek** [googleapis/java-dialogflow#25]
Tenho um app que utiliza da biblioteca do Firestore e também precisa utilizar a do DialogFlow, até o momento estou utilizando a [biblioteca V1](https://github.com/dialogflow/dialogflow-android-client) e não enfrento quaisquer problemas, porém, como a V1 do DialogFlow vai ser encerrada em breve, preciso migrar para a V2. Em minhas tentativas de utilizar esta biblioteca juntamente com o Firestore, enfrento problemas de duplicação de classes.

O problema deve-se a que esta lib usa de  protobuf-java e a do firestore, protobuf-lite, ambas fornecem as mesmas classes com implementações diferentes

Já verifiquei [esse](https://github.com/googleapis/google-cloud-java/issues/5608) tópico que fala sobre, mas implementando a solução sugerida 

`configurations.all {
          exclude group:'com.google.api.grpc',module:'proto-google-common-protos'
          exclude group: 'com.google.protobuf', module: 'protobuf-java'
          exclude group: 'com.google.guava',module: 'guava-jdk5'
      }`

Tenho o seguinte erro 
```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.google.cloud.dialogflow.v2beta1.QueryInput, unresolved supertypes: com.google.protobuf.GeneratedMessageV3
    class com.google.cloud.dialogflow.v2beta1.QueryInputOrBuilder, unresolved supertypes: com.google.protobuf.MessageOrBuilder
    class com.google.cloud.dialogflow.v2beta1.TextInput, unresolved supertypes: com.google.protobuf.GeneratedMessageV3
    class com.google.cloud.dialogflow.v2beta1.TextInputOrBuilder, unresolved supertypes: com.google.protobuf.MessageOrBuilder
    class com.google.cloud.dialogflow.v2beta1.TextInput.Builder, unresolved supertypes: com.google.protobuf.GeneratedMessageV3.Builder
    class com.google.cloud.dialogflow.v2beta1.QueryInput.Builder, unresolved supertypes: com.google.protobuf.GeneratedMessageV3.Builder
    class com.google.cloud.dialogflow.v2beta1.DetectIntentResponse, unresolved supertypes: com.google.protobuf.GeneratedMessageV3
    class com.google.cloud.dialogflow.v2beta1.DetectIntentResponseOrBuilder, unresolved supertypes: com.google.protobuf.MessageOrBuilder
```

Existe alguma solução para isso?

**Comment by kaniundungu** [comment]
Here's a great workaround for those who can't wait for an official fix:

https://github.com/protocolbuffers/protobuf/issues/7094#issuecomment-586532060

The idea behind it is to 'fatjar' the proto artifacts in a sequence that overwrites classes that do not work well with firesbase firestore or inappmessaging.

**Comment by b-loved-dreamer** [comment]
This issue may no longer be relevant so I am closing it.
