### ISSUE TITLE
I want to implement TLS 1.3 with Java client of DialogFlow

### ISSUE THREAD

**Issue by Stavan26** [googleapis/java-dialogflow#272]
I want to implement TLS 1.3 with Java client of DialogFlow.
Do we have any sample code ?

**Comment by munkhuushmgl** [comment]
Currently I cannot seem to find any sample code in our repos.

**Comment by b-loved-dreamer** [comment]
I found this [article](https://cloud.google.com/dialogflow/es/docs/fulfillment-mtls#:~:text=The%20network%20traffic%20initiated%20by,sent%20on%20a%20public%20network.&text=With%20mTLS%2C%20both%20the%20client,handshake%2C%20which%20mutually%20proves%20identity.) on TLS support for ```dialogflow```. 

I am closing this issue. Feel free to reopen.
