### ISSUE TITLE
Firebase and Dialogflow conflict

### ISSUE THREAD

**Issue by saadBinZahoor** [googleapis/java-dialogflow#381]
I am having an issue while integrating dialog flow in the existing project which also has a firebase
I also asked the question on StackOverflow but the problem still exists
https://stackoverflow.com/questions/64876582/duplicate-classes-dialogflow

**Comment by suraj-qlogic** [comment]
@saadBinZahoor,Thanks for filling this issue,Would you share your dependencies of your project like ```gradle.build``` along with Dialogflow and firebase version which cause conflict.

**Comment by saadBinZahoor** [comment]
Sorry for the late response as I stopped working on to implement the DialogFlow in my project because the dependencies were throwing errors.

Now I want to try again, below are the details of what did I try

My project also uses firebase SDK  so i though maybe i was getting error due to firebase sdk, i created a new project and added the below dependencies 
**//dialogFlow
    implementation 'com.google.cloud:google-cloud-dialogflow:2.4.0'
    implementation 'io.grpc:grpc-okhttp:1.32.2'**

Boom, the project did build successfully and there were no errors at all.

But back to project which uses firebase sdk as well, i try many method but every time i get the Dublicate classess error and i am not able to move forward

#Try1

gradle file
`
    implementation 'com.google.api-client:google-api-client:1.31.2'`
 ```
java code
   try {

            InputStream stream = context.getResources().openRawResource(R.raw.credential);
            GoogleCredential credentials = GoogleCredential.fromStream(stream)
                    .createScoped(Lists.newArrayList("https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/dialogflow"));
            String projectId =  credentials.getServiceAccountProjectId();
            credentials.refreshToken();
            String token = credentials.getAccessToken();
 

            Log.d("TokenX", "projectId : " + projectId);
            Log.d("TokenX", "token : " + token);
        } catch (Exception e) {
            Log.d("TokenX", "setUpBot: " + e.getMessage() + "--" + e.getLocalizedMessage() + "--" + e.getStackTrace().toString());
        }
        
```
error
This method is not reading the JSON file which is provided by Google Service Account 

#Try2

dependencies
`implementation 'com.google.auth:google-auth-library-oauth2-http:0.22.2'`

java code

 ```
try {


            InputStream stream = context.getResources().openRawResource(R.raw.credential);
            GoogleCredentials credentials = GoogleCredentials.fromStream(stream)
                    .createScoped(Lists.newArrayList("https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/dialogflow"));
            String projectId = ((ServiceAccountCredentials) credentials).getProjectId();
            credentials.refreshAccessToken();*/
            String token = credentials.getAccessToken().getTokenValue();

            Log.d("TokenX", "projectId : " + projectId);
            Log.d("TokenX", "token : " + token);
        } catch (Exception e) {
            Log.d("TokenX", "setUpBot: " + e.getMessage() + "--" + e.getLocalizedMessage() + "--" + e.getStackTrace().toString());
        }
```

error
this code is returning the null token 


try#3

I try to configure the dependencies in different ways but no luck
```

 configurations.implementation.exclude(group: 'com.google.api.grpc', module: 'proto-google-common-protos')
configurations.implementation.exclude(group: 'com.google.protobuf', module: 'protobuf-java') 

 configurations {
    implementation.exclude module:'proto-google-common-protos'
    implementation.exclude module:'protolite-well-known-types'
   implementation.exclude module:'protobuf-lite'
   implementation.exclude module:'protobuf-java'
    implementation.exclude module:'protobuf-javalite'
} 

```


IS THERE IS ANY WAY TO CONNECT WITH DIALOGFLOW FOR ANDROID ALSO ANY RESTFUL API

**Comment by telpirion** [comment]
Thank you for filing this request on the Java client library for Dialogflow. As mentioned by @chingor13, the Dialogflow Java client library is not supported for use on Android. The best architecture for calling Google Cloud APIs from mobile is [here](https://cloud.google.com/community/tutorials/cloud-functions-callable).
