### ISSUE TITLE
Dialogflow @sys.date-period returns wrong date

### ISSUE THREAD

**Issue by fitsie007** [googleapis/java-dialogflow#39]
I am having an issue with date-periods in DialogFlow Java. When I use a term like "Christmas Eve", Dialogflow v2 returns the following object: {"startDate": "2019-12-25T12:00:00-05:00", "endDate" : "2019-12-18T12:00:00-05:00"}.

Am I doing something wrong or is there an error in the system?

**Comment by chingor13** [comment]
Sorry, do you have a code snippet from the Java client that is failing or is this around the data returned by the API directly?

**Comment by fitsie007** [comment]
Hello,
It’s around the use of the @sys.date-perioid entities returning what looks like an incorrect date range.

**Comment by chingor13** [comment]
If it has to do with that specific data being returned from the server, please open a support ticket on the backend service: https://issuetracker.google.com/savedsearches/5300385

**Comment by b-loved-dreamer** [comment]
It looks like this issue may no longer be relevant and so I am closing it. Please reopen if needed.
