### ISSUE TITLE
com.google.cloud.dialogflow.v2.IntentsClient Exception

### ISSUE THREAD

**Issue by TravisHanna** [googleapis/java-dialogflow#552]
Linux
JDK 11
Dialogflow ES

When calling the delete intent API I am getting the following exception:
{"message":"io.grpc.StatusRuntimeException: INVALID_ARGUMENT: 'travel_egencia_benchmark_flights' is not a valid intent ID. Must be a UUID.\ncom.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: 'travel_egencia_benchmark_flights' is not a valid intent ID. Must be a UUID."}

I have looked at the source code and documentation and do not see any mention of UUID's.  I have verified that the specified intent exists.

#### Steps to reproduce

  1. Use createIntent to create an intent
  2. Use deleteIntent to delete the intent that was just created

#### Code example

```java
        IntentName name = IntentName.of(projectId, intentId);
        intentsClient.deleteIntent(name);
```

**Comment by b-loved-dreamer** [comment]
Hi @TravisHanna — thank you for filing this issue. This [resource](https://cloud.google.com/dialogflow/es/docs/reference/rest/v2/projects.agent.intents/delete) provides details about the API to call to delete an intent.

Using the Java Library, you can run code similar to:

```
try(IntentsClient intentsClient = IntentsClient.create()) {
       IntentName name = IntentName.of("[PROJECT]", "[INTENT]");
       intentsClient.deleteIntent(name);
       System.out.println("Deleted intent");
}

1.  Your intent id should have the correct format. 
     This is an example of an intent id: e285e6f3-c2f6-4976-8875-2f1c31ab44d2
   
2. The parameter format for the deleteIntent method should also be correct
      projects/<Project ID>/agent/intents/<Intent ID>

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
