### ISSUE TITLE
Add BargeInConfig support for InputAudioConfig for StreamingAnalyzeContent

### ISSUE THREAD

**Issue by bradleywehmeier** [googleapis/java-dialogflow#986]
v2beta1 `StreamingAnalyzeContent` supports configuration of the Barge-In, however the `BargeInConfig` class is missing and the `InputAudioConfig` class does not have the `setBargeInConfig` setter.
It would be great if this class and setter were added to this library. Thanks!

**Comment by suztomo** [comment]
The client library is generated by the definition of the service. It's very unlikely that certain configuration is not available in client library but available in the service.

This library has moved to https://github.com/googleapis/google-cloud-java repository. Please create an issue if you still think this is a bug.
