### ISSUE TITLE
Java Diagflow: use SessionClient class from dialogflow java client library

### ISSUE THREAD

**Issue by PrasenjitSaha1** [googleapis/java-dialogflow#989]
User doesn't wants to use SessionClient inside try-with-resources. Because in their use case they have to create new SessionClient object and close it after they receive response. 
**Question is** can they use SessionClient singleton bean and reuse it for every request or there are any contradictions?

**_Observation so far:_**
SessionsClient [1]  implements com.google.api.gax.core.BackgroundResource [2]  which extends AutoCloseable [3] 

Since it is an Autocloseable, SessionsClient is meant to be used in try-with-resources blocks by design.

[1] https://github.com/googleapis/java-dialogflow/blob/74759e691efbb9bf84bae44e9de47cb54bb9625c/google-cloud-dialogflow/src/main/java/com/google/cloud/dialogflow/v2/SessionsClient.java#L125

[2] https://github.com/googleapis/gax-java/blob/1f34a608aa4e949a52c4cef74d2123a7266af22c/gax/src/main/java/com/google/api/gax/core/BackgroundResource.java#L38

[3] https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html

**Comment by mkaczor** [comment]
Hi,

according to your [documentation](https://cloud.google.com/dialogflow/cx/docs/concept/best-practices) we should aim at reusing ```SessionsClient```:
![image](https://user-images.githubusercontent.com/15094747/186892224-cc4aa34a-f559-46b4-92ba-b3bf880fdf87.png)
That's how we've implemented it for now, we only call ```SessionsClient#close``` method before shutting down our service. What concerns me is that in your samples you always use 'try-with-resources'. Shall we expect any undesired side effect if we don't do it and reuse one ```SessionsClient``` for a whole app lifetime?

**Comment by mattcarrolldev** [comment]
@PrasenjitSaha1 This Github repo's issues are for reporting problems with the Dialogflow Java client library. For questions on how to use the library, please use another forum, like StackOverflow.
